apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager
          image: uhub.service.ucloud.cn/entropypool/order-manager:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/OrderManager
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: order-manager-config
            items:
              - key: service-conf
                path: OrderManager.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50360
      targetPort: 50360
    - name: grpc
      port: 50361
      targetPort: 50361
    - name: healthz
      port: 50362
      targetPort: 50362
    - name: prometheus
      port: 50363
      targetPort: 50363
  selector:
    app: order-manager
